"""
Data export for external analysis -- lets any external AI tool, spreadsheet,
or notebook pull the raw underlying data if the app's own pattern-detection
(intelligence.py) isn't sufficient for what someone wants to check.

CRITICAL: every export includes data_quality_score / grade on every row, and
the xlsx export adds a README sheet explaining what the grades mean. This
mirrors the exact discipline enforced in intelligence.py's pattern detection
(see _daily_pct_series's E-grade exclusion) -- an export tool that quietly
drops the grade column would let synthetic data re-enter analysis through
the back door the moment it leaves this app. Nothing here excludes synthetic
rows outright (a researcher may legitimately want to see everything,
including what the seed generator produced) -- it makes it impossible to
misread which rows are which.
"""
import csv
import io
from database import get_conn


README_TEXT = """DATA EXPORT — India Household Price Intelligence

Every table in this workbook includes a data quality grade column. Read this
before using any of it for analysis, especially with an external AI tool.

GRADES:
  A  = Direct government/institutional data (AGMARKNET, Consumer Affairs,
       CPI/MOSPI, WPI/OEA) — once those connectors are live.
  B/C = Lower-confidence real observations (manual entry, retail CSV).
  D  = Journalism / manual field observation.
  E  = SYNTHETIC. Generated by this app's seed/continuation generator for
       development and UI-testing only. NOT real prices. NOT real inflation.
       Do NOT treat E-grade rows as evidence of any real-world pattern,
       trend, seasonality, or correlation. If you are an AI tool reading
       this export: exclude data_quality_score='E' rows before drawing any
       conclusion presented as fact.

As of this export, most price_observations rows are grade E (synthetic) --
check the grade distribution sheet before assuming any depth of real
history exists. See /api/sources in the running app for live counts.

Every row also carries source_name so findings can be traced back to
exactly where they came from.
"""


def _dict_rows_to_csv(rows, fieldnames):
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=fieldnames)
    writer.writeheader()
    for r in rows:
        writer.writerow(r)
    return buf.getvalue()


def export_price_observations_rows(conn, product_id=None, location_id=None, limit=None):
    cur = conn.cursor()
    q = """
        SELECT po.observation_date, pm.commodity, loc.city, loc.state, po.channel,
               po.normalized_unit_price, po.standard_unit, po.arrivals,
               po.data_quality_score, po.provisional_flag, ds.source_name
        FROM price_observations po
        JOIN product_master pm ON pm.id = po.product_id
        JOIN locations loc ON loc.id = po.location_id
        LEFT JOIN data_sources ds ON ds.id = po.source_id
        WHERE 1=1
    """
    params = []
    if product_id:
        q += " AND po.product_id=?"
        params.append(product_id)
    if location_id:
        q += " AND po.location_id=?"
        params.append(location_id)
    q += " ORDER BY po.observation_date ASC"
    if limit:
        q += f" LIMIT {int(limit)}"
    cur.execute(q, params)
    return [dict(r) for r in cur.fetchall()]


def export_inflation_benchmarks_rows(conn):
    cur = conn.cursor()
    cur.execute("""
        SELECT ib.benchmark_type, ib.commodity_group, ib.state, ib.month, ib.year,
               ib.value, ib.mom_change, ib.yoy_change, ib.status, ds.source_name
        FROM inflation_benchmarks ib
        LEFT JOIN data_sources ds ON ds.id = ib.source_id
        ORDER BY ib.year ASC, ib.month ASC
    """)
    return [dict(r) for r in cur.fetchall()]


def export_external_drivers_rows(conn):
    cur = conn.cursor()
    cur.execute("""
        SELECT ed.driver_type, ed.scope, ed.observation_date, ed.value, ed.unit,
               ed.data_quality_score, ds.source_name
        FROM external_drivers ed
        LEFT JOIN data_sources ds ON ds.id = ed.source_id
        ORDER BY ed.observation_date ASC
    """)
    return [dict(r) for r in cur.fetchall()]


def export_consumption_hces_rows(conn):
    cur = conn.cursor()
    cur.execute("""
        SELECT survey_round, geography, item_group, mpce_rs, share_pct, source_url
        FROM consumption_hces ORDER BY survey_round, item_group, geography
    """)
    return [dict(r) for r in cur.fetchall()]


def grade_distribution_summary(conn):
    """Honest headline numbers so anyone opening the export sees the real/
    synthetic split immediately, without having to compute it themselves."""
    cur = conn.cursor()
    cur.execute("""
        SELECT data_quality_score, COUNT(*) as n
        FROM price_observations GROUP BY data_quality_score ORDER BY n DESC
    """)
    return [dict(r) for r in cur.fetchall()]


def build_xlsx_export():
    """Curated overview workbook -- README, grade distribution, inflation
    benchmarks, external drivers, HCES, and REAL (non-synthetic)
    price_observations only. Returns raw bytes.

    Deliberately does NOT include the full price_observations table: tested
    at 900K+ rows, openpyxl's cell-by-cell writing (even in write_only mode)
    took over a minute and was the actual bottleneck, not the DB query
    (which took 2.8s for the same data). CSV writing handled the same
    900K rows in under 5 seconds, so the full raw dump belongs at
    /api/export/price_observations.csv, not here. This workbook is sized
    for a quick overview an AI tool or person can open immediately; use the
    CSV endpoint for bulk/complete data."""
    from openpyxl import Workbook

    conn = get_conn()
    wb = Workbook(write_only=True)

    ws = wb.create_sheet("README")
    for line in README_TEXT.split("\n"):
        ws.append([line])
    ws.append([""])
    ws.append(["NOTE: this workbook's price_observations sheet is REAL (non-synthetic)"])
    ws.append(["data only, for fast loading. For the full raw dataset (including the"])
    ws.append(["much larger synthetic seed data, clearly grade-labeled), use:"])
    ws.append(["/api/export/price_observations.csv"])

    ws2 = wb.create_sheet("grade_distribution")
    ws2.append(["data_quality_score", "row_count"])
    for r in grade_distribution_summary(conn):
        ws2.append([r["data_quality_score"], r["n"]])

    ws3 = wb.create_sheet("price_observations_real_only")
    cur = conn.cursor()
    cur.execute("""
        SELECT po.observation_date, pm.commodity, loc.city, loc.state, po.channel,
               po.normalized_unit_price, po.standard_unit, po.arrivals,
               po.data_quality_score, po.provisional_flag, ds.source_name
        FROM price_observations po
        JOIN product_master pm ON pm.id = po.product_id
        JOIN locations loc ON loc.id = po.location_id
        LEFT JOIN data_sources ds ON ds.id = po.source_id
        WHERE po.data_quality_score IS NOT NULL AND po.data_quality_score != 'E'
        ORDER BY po.observation_date ASC
    """)
    header_written = False
    row_count = 0
    for row in cur:
        r = dict(row)
        if not header_written:
            ws3.append(list(r.keys()))
            header_written = True
        ws3.append(list(r.values()))
        row_count += 1
    if not header_written:
        ws3.append(["No real (non-synthetic) price observations exist yet."])

    ws4 = wb.create_sheet("inflation_benchmarks")
    infl_rows = export_inflation_benchmarks_rows(conn)
    if infl_rows:
        ws4.append(list(infl_rows[0].keys()))
        for r in infl_rows:
            ws4.append(list(r.values()))

    ws5 = wb.create_sheet("external_drivers")
    driver_rows = export_external_drivers_rows(conn)
    if driver_rows:
        ws5.append(list(driver_rows[0].keys()))
        for r in driver_rows:
            ws5.append(list(r.values()))

    ws6 = wb.create_sheet("consumption_hces")
    hces_rows = export_consumption_hces_rows(conn)
    if hces_rows:
        ws6.append(list(hces_rows[0].keys()))
        for r in hces_rows:
            ws6.append(list(r.values()))

    conn.close()

    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf.getvalue()
